version: '3.2'
services:
  proftpd:
    env_file: .env
    image: ebarault/proftpd-docker:alpine-latest
    network_mode: host
    volumes:
      - type: bind
        source: "${LOGS:-/var/log/proftpd}"
        target: /var/log/proftpd
      - type: bind
        source: "${FTP_ROOT:-/data/ftp_root}"
        target: /srv/ftp
      - type: bind
        source: "${SSL_CERTS:-./ssl}"
        target: /etc/proftpd/ssl
      - type: bind
        source: "${MOD_EXEC_CONF:-./exec}"
        target: "/etc/proftpd/exec"
      - type: bind
        source: "${SALT:-./salt}"
        target: "/etc/proftpd/salt"
