version: '3.2'
services:
  proftpd:
    container_name: proftpd
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile-alpine
    network_mode: host
    volumes:
      - type: bind
        source: "${LOGS:-/var/log/proftpd}"
        target: /var/log/proftpd
      - type: bind
        source: "${FTP_ROOT:-/data/ftp_root}"
        target: /srv/ftp
      - type: bind
        source: "${MOD_TLS_CONF:-./tls.conf}"
        target: /etc/proftpd/tls.conf
      - type: bind
        source: "${CERTS:-./certs}"
        target: /etc/proftpd/certs
      - type: bind
        source: "${MOD_EXEC_CONF:-./exec}"
        target: "/etc/proftpd/exec"
      - type: bind
        source: "${SALT:-./salt}"
        target: "/etc/proftpd/salt"
      - type: bind
        source: "${MOD_VROOT_CONF:-./vroot}"
        target: "/etc/proftpd/vroot"
